# Generated by Django 6.0.2 on 2026-04-07 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_exam'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='completed_topics',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='total_topics',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_hours', models.FloatField(default=0)),
                ('tuesday_hours', models.FloatField(default=0)),
                ('wednesday_hours', models.FloatField(default=0)),
                ('thursday_hours', models.FloatField(default=0)),
                ('friday_hours', models.FloatField(default=0)),
                ('saturday_hours', models.FloatField(default=0)),
                ('sunday_hours', models.FloatField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
